import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FSD Task 1",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
    initialScale: 1,
    width: "device-width"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter} antialiased`}
      >
        <nav className="bg-accent text-white p-8 md:flex md:items-center md:justify-between">
            <span className="text-2xl">FSD Task 1</span>
            <div className="text-lg">
                <Link href="/" className="mr-4 md:mr-0 md:ml-6">Home</Link>
                <Link href="/register" className="mr-4 md:mr-0 md:ml-6">Register</Link>
            </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
